// <auto-generated />
using System;
using GamesStrategApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GamesStrategApi.Migrations
{
    [DbContext(typeof(StrategContext))]
    [Migration("20251215075450_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GamesStrategApi.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("IncomeBonus")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProductionCost")
                        .HasColumnType("integer");

                    b.Property<int?>("UnlockingTechId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UnlockingTechId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("GamesStrategApi.Models.CelestialBody", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PositionX")
                        .HasColumnType("integer");

                    b.Property<int>("PositionY")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceRichness")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("CelestialBodies");
                });

            modelBuilder.Entity("GamesStrategApi.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("HomeWorldType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsPlayable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UniqueBonus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("GamesStrategApi.Models.Tech", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("RequiredTechId")
                        .HasColumnType("integer");

                    b.Property<int>("ResearchCost")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequiredTechId");

                    b.ToTable("Techs");
                });

            modelBuilder.Entity("GamesStrategApi.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<int>("MovementSpeed")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProductionCost")
                        .HasColumnType("integer");

                    b.Property<int?>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("Shield")
                        .HasColumnType("integer");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("UnlockingTechId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.HasIndex("UnlockingTechId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("GamesStrategApi.Models.Building", b =>
                {
                    b.HasOne("GamesStrategApi.Models.Tech", "UnlockingTech")
                        .WithMany("Buildings")
                        .HasForeignKey("UnlockingTechId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UnlockingTech");
                });

            modelBuilder.Entity("GamesStrategApi.Models.Tech", b =>
                {
                    b.HasOne("GamesStrategApi.Models.Tech", "RequiredTech")
                        .WithMany("UnlockedTechs")
                        .HasForeignKey("RequiredTechId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RequiredTech");
                });

            modelBuilder.Entity("GamesStrategApi.Models.Unit", b =>
                {
                    b.HasOne("GamesStrategApi.Models.Race", "Race")
                        .WithMany("Units")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GamesStrategApi.Models.Tech", "UnlockingTech")
                        .WithMany("Units")
                        .HasForeignKey("UnlockingTechId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Race");

                    b.Navigation("UnlockingTech");
                });

            modelBuilder.Entity("GamesStrategApi.Models.Race", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("GamesStrategApi.Models.Tech", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Units");

                    b.Navigation("UnlockedTechs");
                });
#pragma warning restore 612, 618
        }
    }
}
